### ISSUE TITLE
React + Hot Reload - Doesn't work after exporting in it's update!

### ISSUE THREAD

**Issue by kosiakMD** [maxfarseer/redux-ru-tutorial#2]
Module build failed: Error: React Hot Loader: The Webpack loader is now exported separately. If you use Babel, we recommend that you remove "react-hot-loader" from the "loaders" section of your Webpack configuration altogether, and instead add "react-hot-loader/babel" to the "plugins" section of your .babelrc file. If you prefer not to use Babel, replace "react-hot-loader" or "react-hot" with "react-hot-loader/webpack" in the "loaders" section of your Webpack configuration.
    at Object.warnAboutIncorrectUsage (/Users/{USER}/{Desktop}/{Projects}/{redux_test}/node_modules/react-hot-loader/lib/index.js:7:11)
 @ multi main

was added "react-hot-loader/babel" to the "plugins" section of your .babelrc file
and/or replaced "react-hot-loader" or "react-hot" with "react-hot-loader/webpack" in the "loaders" section of my Webpack configuration.

NOTHING HELPED!

**Comment by maxfarseer** [comment]
Try to use old versions of packages (see package.json file)

**Comment by kosiakMD** [comment]
Good for the first time ;)
It would be great if you'll resolve this issue!

**Comment by suprekaka** [comment]
It seems that you use the react-hot-loader@3.0.0-beta.x
You can use react-hot-loader@1.3.0 to solve this problem.
If you want to use the new features, please refer to https://github.com/gaearon/react-hot-boilerplate/tree/next (note the branch is next).

You must have below code in your app container : 

``` js
const rootEl = document.getElementById('root');
ReactDOM.render(
  <AppContainer>
    <App />
  </AppContainer>,
  rootEl
);

if (module.hot) {
  module.hot.accept('./App', () => {
    // If you use Webpack 2 in ES modules mode, you can
    // use <App /> here rather than require() a <NextApp />.
    const NextApp = require('./App').default;
    ReactDOM.render(
      <AppContainer>
         <NextApp />
      </AppContainer>,
      rootEl
    );
  });
}
```
