### ISSUE TITLE
refs with redux Actions

### ISSUE THREAD

**Issue by kosiakMD** [maxfarseer/redux-ru-tutorial#3]
Здравствуйте, решил писать на русском - думаю так будет проще ;)
Если Вы не против.
Изучаю Redux и решил пойти дальше, добавил форму логина и хотел использовать refs для получения значений из полей формы. Но тут оказалось не все просто. Ведь refs доступны только локально в модуле.
Я решил это следующим образом:

**components/ser.js**

```
...some code...

export default class User extends Component {
    handleSubmit(event){
        event.preventDefault();
        this.props.handleLogin(this.refs);
    }

    ...some code...

    template = <div>
            <form className='' onSubmit={this.handleSubmit.bind(this)} >
                <input type='text' placeholder='login' ref='login_input'/>
                <input type='password' placeholder='password' ref='password_input'/>
                <button type='submit' className='btn' onClick=''>Login</button>
            </form>
        </div>`
```

**ations/UserActions.js**

```
import ReactDOM from 'react-dom';
...some code...

export function handleLogin(refs) {
...some code...

    const login = ReactDOM.findDOMNode(refs.login_input).value.trim();
    const password = ReactDOM.findDOMNode(refs.password_input).value.trim();
...some code...
```

Есть ли способ по-легче обрабатывать input'ы форм?
Может в объявлять через 'const'? Правда если будет много форм\полей , то и путаницы не избежать.

**Comment by maxfarseer** [comment]
День добрый.
1) лучше передавайте сразу объект, например:

``` js
...
const login = ReactDOM.findDOMNode(refs.login_input).value.trim();
const password = ReactDOM.findDOMNode(refs.password_input).value.trim();
const params = { login, password } // тоже самое, что и {login: login, password: password}
...
 this.props.handleLogin(params)
....
```

2) так же можете использовать state, и так же собирайте из него объект params.

Передавать объект refs не вижу смысла, так как могут быть такие ref'ы, которые вы не захотите передавать. Передавать сразу объект с параметрами (даже собранными из тех же refs) самое то!

P.S. если что пишите на "[тостер](https://toster.ru/)"
